"""Compute + author a scene's verified room connectivity graph (Kit-bound).

Sibling to ``extract_scene_metadata.py`` — kept separate so the
Infinigen-state-walker stays pure. This step runs *after* metadata authoring
in the scene-gen pipeline and produces two artifacts:

1. A cached occupancy grid (``<scene>/occupancy.npy`` + ``occupancy.json``).
   Generated by Isaac Sim's occupancy-map extension (Isaac Sim 6.x
   ``isaacsim.asset.gen.omap``; the 5.x ``omni.isaac.occupancy_map`` is its
   predecessor), which reads the stage's *physics colliders* — so it sees the
   doorway free-space the floor/object-AABB rasterizer would miss. This grid
   is a regenerable derived intermediate (not authored metadata): ``occupancy
   .json`` records the grid→world mapping plus the source-USD identity so a
   stale grid is detectable. It is the **shared occupancy seam** the other
   Infinigen path-planning consumers (mission-generator oracle,
   grounding-negative trajectory checks) load instead of re-rasterizing — see
   :mod:`strafer_lab.tools.scene_connectivity` and
   ``docs/tasks/context/path-planning-architecture.md``.

2. A ``connectivity[]`` block + ``multi_story`` flag merged into the scene
   USD's root-prim ``customData`` (the authored metadata; no JSON sidecar).
   Each edge is an undirected room pair (``from_idx`` < ``to_idx``, indices
   into ``rooms[]`` — not ``room_type`` strings, since rooms can share a
   type):

       reachable:   {from_idx, to_idx, reachable: true, via_doorway_xy,
                     path_length_m, door_state}
       unreachable: {from_idx, to_idx, reachable: false, reason}

   ``reason`` is ``"stairs"`` (cross-story; the mecanum strafer can't climb)
   or ``"blocked"`` (no collision-free path even with doors open). The strafer
   has no manipulator, so every door is opened at scene-gen time (the brief's
   "doors assumed open"): the collider is dropped *before* occupancy generation
   and the leaf panel mesh is hidden so the visual matches the open passage.
   Both are persisted. ``door_state`` on a reachable edge is then
   ``"force-opened"`` (a door prim sits on the crossing) or ``"absent"`` (an
   open gap, no door). Cross-story scenes also set ``multi_story: true`` at the
   top level. A scene is tagged ``multi_room_incompatible: true`` only when it
   has cross-room candidate pairs but *none* is reachable.

   A room sealed only by a doorway whose wall-cutout the postprocess
   ``meshSimplification`` collider heals shut can still read as occupied (the
   omap's flood treats the enclosed interior as occupied, not free); that is a
   known occupancy-fidelity limitation tracked as a follow-up, not a
   door-matching gap.

Reachability is decided by the project's one shared grid planner
(``plan_path``) over the inflated occupancy — this brief writes a grid
adapter, not a second A*.

Room geometry: the per-room footprints come from the authored ``rooms[]``
when present; otherwise they are recovered from the per-room Infinigen floor
meshes (``<room_type>_<story>_<index>_floor``) and back-filled into the
metadata, so a scene whose metadata was authored from USD prim names alone
(``rooms == []``) still gets a connectivity graph.

If the occupancy-map extension is unavailable, pass ``--rasterize-fallback``
to build the occupancy from the room footprints + object AABBs instead (the
brief's documented fallback); the output is the same free-space grid.

Usage::

    $ISAACLAB -p source/strafer_lab/scripts/validate_scene_connectivity.py \\
        --usd Assets/generated/scenes/<scene>.usdc
"""

from __future__ import annotations

import argparse
import datetime
import os
import json
import logging
import math
import re
import sys
import traceback
from pathlib import Path
from typing import Any

import numpy as np

from strafer_lab.tools import scene_connectivity, scene_metadata_reader

logger = logging.getLogger("validate_scene_connectivity")

# Kit replaces the root logging config on boot and redirects sys.stdout, so the
# standard logger is unreliable for milestones. _trace writes straight to a file
# (and the *original* stderr) which Kit cannot clobber.
_TRACE_PATH: Path | None = None


def _trace(msg: str) -> None:
    logger.info(msg)
    line = f"{datetime.datetime.now().isoformat()} {msg}\n"
    try:
        sys.__stderr__.write(line)
        sys.__stderr__.flush()
    except Exception:  # noqa: BLE001
        pass
    if _TRACE_PATH is not None:
        with open(_TRACE_PATH, "a", encoding="utf-8") as fh:
            fh.write(line)

# Infinigen door factories (PanelDoor / LiteDoor / LouverDoor / GlassPanelDoor,
# both the frame ``__spawn_asset_N_`` and leaf ``__spawn_asset_N__001`` prims).
# Verified against seed1/seed2: this catches every door-named prim in both scenes
# (incl. the GlassPanel variant), so there is no door the door-open pass misses.
_DOOR_PRIM_RE = re.compile(r"Door[A-Za-z]*Factory_\d+__spawn_asset_\d+_")
# The leaf is the swinging panel (extra ``__NNN`` suffix); the frame is the casing.
_DOOR_LEAF_RE = re.compile(r"__spawn_asset_\d+__\d+$")

# Occupancy slab, measured above the floor.
#   z_lo: just above the floor — clears the floor plane (its colliders are stripped
#         in postprocess anyway) plus any door-sill / transition-strip lip.
#   z_hi: the robot's vertical envelope (floor → top of the camera mast). An
#         obstacle in this band can collide; anything above it (a tabletop) the
#         robot drives under, so the slab stops there. Derived from the shared
#         chassis constants so it tracks the real robot, not a magic number.
try:
    from strafer_shared.constants import (  # noqa: WPS433
        CAMERA_HEIGHT,
        CAMERA_OFFSET_Z,
        CHASSIS_GROUND_CLEARANCE,
        CHASSIS_HEIGHT,
    )

    _ROBOT_TOP_M = (
        CHASSIS_GROUND_CLEARANCE + CHASSIS_HEIGHT + CAMERA_OFFSET_Z + CAMERA_HEIGHT
    )
except Exception:  # pragma: no cover - strafer_shared always present in lab env
    _ROBOT_TOP_M = 0.34
_DEFAULT_Z_LO_M = 0.05
_DEFAULT_Z_HI_M = round(_ROBOT_TOP_M, 3)  # ~0.34 m above the floor

# Occupancy bounds are padded past the floor-mesh AABBs so the room walls (which
# sit at / just outside the floor edge) land inside the grid rather than being
# clipped at the boundary. 1.5 m comfortably exceeds wall thickness + a doorway's
# outward reach.
_DEFAULT_PAD_M = 1.5

# A door prim counts as "on" a doorway crossing if its center is within this of
# the path's estimated crossing point: ~half a standard door width plus the
# crossing-estimate slop, tight enough not to grab a neighbouring door.
_DOOR_NEAR_DOORWAY_M = 0.7


# ---------------------------------------------------------------------------
# USD geometry recovery (pxr / Kit)
# ---------------------------------------------------------------------------


def _xy_bbox(prim: Any, bbox_cache: Any) -> tuple[float, float, float, float, float] | None:
    """Return ``(min_x, min_y, max_x, max_y, mid_z)`` world AABB or ``None``."""
    try:
        rng = bbox_cache.ComputeWorldBound(prim).ComputeAlignedRange()
        if rng.IsEmpty():
            return None
        mn, mx = rng.GetMin(), rng.GetMax()
        return float(mn[0]), float(mn[1]), float(mx[0]), float(mx[1]), float(0.5 * (mn[2] + mx[2]))
    except Exception:  # noqa: BLE001 - USD bbox can throw on malformed prims
        return None


def recover_rooms_from_floors(stage: Any) -> tuple[list[dict[str, Any]], float]:
    """Recover ``rooms[]`` from per-room Infinigen floor meshes.

    Returns ``(rooms, floor_z)`` where each room carries ``room_type``,
    ``story``, ``footprint_xy`` (the floor mesh's XY AABB as a rectangle) and
    ``area_m2``. ``floor_z`` is the median floor height (the occupancy z-slab
    reference).
    """
    from pxr import Usd, UsdGeom  # type: ignore

    bbox_cache = UsdGeom.BBoxCache(
        Usd.TimeCode.Default(), [UsdGeom.Tokens.default_], useExtentsHint=True
    )
    rooms: list[dict[str, Any]] = []
    floor_zs: list[float] = []
    for prim in stage.Traverse():
        if not prim.IsValid() or prim.GetTypeName() != "Mesh":
            continue
        parsed = scene_connectivity.parse_room_floor_name(prim.GetName())
        if parsed is None:
            continue
        box = _xy_bbox(prim, bbox_cache)
        if box is None:
            continue
        min_x, min_y, max_x, max_y, mid_z = box
        room_type, story, _index = parsed
        footprint = scene_connectivity.aabb_to_footprint((min_x, min_y), (max_x, max_y))
        rooms.append(
            {
                "room_type": room_type,
                "story": story,
                "footprint_xy": footprint,
                "area_m2": round((max_x - min_x) * (max_y - min_y), 4),
            }
        )
        floor_zs.append(mid_z)
    floor_z = float(np.median(floor_zs)) if floor_zs else 0.0
    logger.info("Recovered %d rooms from floor meshes (floor_z=%.3f)", len(rooms), floor_z)
    return rooms, floor_z


def collect_door_prims(stage: Any) -> list[dict[str, Any]]:
    """Return door prims with their XY AABB center + leaf flag.

    ``center_xy`` is used for door_state tagging; ``is_leaf`` (the swinging
    panel, ``__NNN`` suffix) is hidden so the visual matches the now-passable
    doorway.
    """
    from pxr import Usd, UsdGeom  # type: ignore

    bbox_cache = UsdGeom.BBoxCache(
        Usd.TimeCode.Default(), [UsdGeom.Tokens.default_], useExtentsHint=True
    )
    doors: list[dict[str, Any]] = []
    seen: set[str] = set()
    for prim in stage.Traverse():
        if not prim.IsValid():
            continue
        name = prim.GetName()
        if not _DOOR_PRIM_RE.search(name):
            continue
        if name in seen:  # collapse the Xform/Mesh twin
            continue
        box = _xy_bbox(prim, bbox_cache)
        if box is None:
            continue
        seen.add(name)
        min_x, min_y, max_x, max_y, _mid_z = box
        doors.append(
            {
                "path": str(prim.GetPath()),
                "center_xy": (0.5 * (min_x + max_x), 0.5 * (min_y + max_y)),
                "is_leaf": bool(_DOOR_LEAF_RE.search(name)),
            }
        )
    logger.info("Found %d door prims (%d leaves)", len(doors), sum(d["is_leaf"] for d in doors))
    return doors


def _scene_bounds(rooms: list[dict[str, Any]], pad_m: float) -> tuple[float, float, float, float]:
    pts = np.concatenate([np.asarray(r["footprint_xy"], dtype=float) for r in rooms])
    return (
        float(pts[:, 0].min()) - pad_m,
        float(pts[:, 1].min()) - pad_m,
        float(pts[:, 0].max()) + pad_m,
        float(pts[:, 1].max()) + pad_m,
    )


# ---------------------------------------------------------------------------
# Occupancy generation
# ---------------------------------------------------------------------------


def _occupancy_from_points(
    points: Any, *, bounds: tuple[float, float, float, float], cell_size: float
) -> tuple[np.ndarray, tuple[float, float]]:
    """Rasterize occupied world positions into a planner-convention grid.

    ``grid[row, col]`` with ``row`` indexing world +X, ``col`` +Y, origin at
    ``(min_x, min_y)``. 1 = occupied.
    """
    min_x, min_y, max_x, max_y = bounds
    nx = max(1, int(math.ceil((max_x - min_x) / cell_size)))
    ny = max(1, int(math.ceil((max_y - min_y) / cell_size)))
    grid = np.zeros((nx, ny), dtype=np.uint8)
    for p in points:
        r = int((float(p[0]) - min_x) / cell_size)
        c = int((float(p[1]) - min_y) / cell_size)
        if 0 <= r < nx and 0 <= c < ny:
            grid[r, c] = 1
    return grid, (min_x, min_y)


def generate_occupancy_omap(
    simulation_app: Any,
    *,
    bounds: tuple[float, float, float, float],
    z_min: float,
    z_max: float,
    cell_size: float,
) -> tuple[np.ndarray, tuple[float, float]]:
    """Generate occupancy via the Isaac Sim occupancy-map extension.

    Reads the stage's physics colliders over the z-slab ``[z_min, z_max]`` and
    rasterizes the occupied cells into a planner-convention grid.
    """
    import omni.timeline  # type: ignore
    from isaacsim.asset.gen.omap.bindings import _omap  # type: ignore
    from isaacsim.asset.gen.omap.utils import update_location  # type: ignore

    min_x, min_y, max_x, max_y = bounds
    om = _omap.acquire_omap_interface()
    timeline = omni.timeline.get_timeline_interface()

    # Slab anchored at the min corner; bounds are relative to that origin.
    update_location(
        om,
        (min_x, min_y, z_min),
        (0.0, 0.0, 0.0),
        (max_x - min_x, max_y - min_y, z_max - z_min),
    )
    om.set_cell_size(cell_size)

    timeline.play()
    # Kit settle-pumps (empirical / conservative, tied to the Kit-timeline
    # gotchas): 8 frames let PhysX cook the colliders + the door-collider drop
    # propagate before the map is built; 2 frames flush the omap result before we
    # read it. Too few risks an occupancy from a half-cooked scene.
    for _ in range(8):
        simulation_app.update()
    om.generate()
    for _ in range(2):
        simulation_app.update()
    points = om.get_occupied_positions()
    timeline.stop()
    logger.info("omap generated %d occupied cells", len(points))
    return _occupancy_from_points(points, bounds=bounds, cell_size=cell_size)


def generate_occupancy_rasterize(
    stage: Any,
    rooms: list[dict[str, Any]],
    metadata: dict[str, Any],
    *,
    bounds: tuple[float, float, float, float],
    z_min: float,
    z_max: float,
    cell_size: float,
) -> tuple[np.ndarray, tuple[float, float]]:
    """Fallback: rasterize room footprints + object AABBs into occupancy.

    Documented fallback for when the occupancy-map extension is unavailable.
    Marks everything outside the room footprints as occupied (so the exterior
    is non-navigable), then carves object AABBs (intersecting the z-slab) back
    in as occupied obstacles. Misses collision-only doorway geometry the omap
    path captures — hence the fallback, not the default.
    """
    min_x, min_y, max_x, max_y = bounds
    nx = max(1, int(math.ceil((max_x - min_x) / cell_size)))
    ny = max(1, int(math.ceil((max_y - min_y) / cell_size)))
    # Start fully occupied; free out the interior of each room footprint.
    grid = np.ones((nx, ny), dtype=np.uint8)
    xs = (np.arange(nx) + 0.5) * cell_size + min_x
    ys = (np.arange(ny) + 0.5) * cell_size + min_y
    gx, gy = np.meshgrid(xs, ys, indexing="ij")
    for room in rooms:
        fp = room["footprint_xy"]
        rx = [p[0] for p in fp]
        ry = [p[1] for p in fp]
        inside = (gx >= min(rx)) & (gx <= max(rx)) & (gy >= min(ry)) & (gy <= max(ry))
        grid[inside] = 0
    # Re-occupy object AABBs that intersect the slab.
    for obj in metadata.get("objects", []) or []:
        bmin = obj.get("bbox_3d_min") or obj.get("bbox_3d", {}).get("min")
        bmax = obj.get("bbox_3d_max") or obj.get("bbox_3d", {}).get("max")
        if not bmin or not bmax:
            continue
        if bmax[2] < z_min or bmin[2] > z_max:
            continue
        inside = (gx >= bmin[0]) & (gx <= bmax[0]) & (gy >= bmin[1]) & (gy <= bmax[1])
        grid[inside] = 1
    return grid, (min_x, min_y)


# ---------------------------------------------------------------------------
# Door-open verification + door-state tagging
# ---------------------------------------------------------------------------


def drop_door_colliders(stage: Any, door_paths: list[str]) -> int:
    """Remove collision APIs from door prims (and their mesh children)."""
    from pxr import UsdPhysics  # type: ignore

    count = 0
    for path in door_paths:
        root = stage.GetPrimAtPath(path)
        if not root or not root.IsValid():
            continue
        for prim in [root, *root.GetChildren()]:
            had = False
            if prim.HasAPI(UsdPhysics.MeshCollisionAPI):
                prim.RemoveAPI(UsdPhysics.MeshCollisionAPI)
                had = True
            if prim.HasAPI(UsdPhysics.CollisionAPI):
                prim.RemoveAPI(UsdPhysics.CollisionAPI)
                had = True
            count += int(had)
    return count


def hide_door_leaves(stage: Any, leaf_paths: list[str]) -> int:
    """Make the door-leaf (swinging panel) meshes invisible.

    A dropped collider makes the doorway passable, but the panel mesh stays
    shut visually — a camera capturing a demo would film the robot driving
    *through* a closed-looking door, teaching "closed doors are passable". So
    the leaf panel is hidden (the frame casing stays) and the doorway reads as
    an open passage. Persisted on save.
    """
    from pxr import UsdGeom  # type: ignore

    count = 0
    for path in leaf_paths:
        prim = stage.GetPrimAtPath(path)
        if not prim or not prim.IsValid():
            continue
        UsdGeom.Imageable(prim).MakeInvisible()
        count += 1
    return count


def _door_at_crossing(edge: dict[str, Any], doors: list[dict[str, Any]]) -> bool:
    """True if a door prim sits on this edge's doorway crossing point."""
    via = edge.get("via_doorway_xy")
    if not via:
        return False
    vx, vy = via
    return any(
        math.hypot(d["center_xy"][0] - vx, d["center_xy"][1] - vy) <= _DOOR_NEAR_DOORWAY_M
        for d in doors
    )


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------


def _wait_for_stage_load(ctx: Any, simulation_app: Any, *, max_updates: int = 6000) -> None:
    """Pump Kit updates until the (async) stage finishes loading.

    A multi-GB Infinigen USD streams in over many frames; traversing it before
    load completes finds zero floor meshes. ``get_stage_loading_status`` returns
    ``(message, files_loaded, files_to_load)`` — wait for nothing left to load.
    """
    for i in range(max_updates):
        status = ctx.get_stage_loading_status()
        if status[2] <= 0:
            logger.info("stage loaded after %d update(s)", i)
            return
        simulation_app.update()
    logger.warning("stage still loading after %d updates; proceeding", max_updates)


def _scene_dir_for(usd_path: Path) -> Path:
    """Resolve the per-scene directory (where occupancy.npy is cached)."""
    resolved = usd_path.resolve()
    for parent in resolved.parents:
        if parent.name.startswith("scene_") and parent.parent.name == "scenes":
            return parent
    return resolved.parent


def _format_matrix(rooms: list[dict[str, Any]], edges: list[dict[str, Any]]) -> str:
    mat = scene_connectivity.connectivity_matrix(len(rooms), edges)
    labels = [f"{i}:{r.get('room_type', '?')}" for i, r in enumerate(rooms)]
    width = max((len(l) for l in labels), default=3)
    header = " " * (width + 1) + " ".join(f"{i:>2}" for i in range(len(rooms)))
    lines = [header]
    for i, lab in enumerate(labels):
        cells = " ".join(" ." if not mat[i, j] else " #" for j in range(len(rooms)))
        lines.append(f"{lab:<{width}} {cells}")
    return "\n".join(lines)


def validate_connectivity(
    usd_path: Path,
    *,
    simulation_app: Any,
    cell_size: float = scene_connectivity.DEFAULT_RESOLUTION_M,
    pad_m: float = _DEFAULT_PAD_M,
    z_lo_m: float = _DEFAULT_Z_LO_M,
    z_hi_m: float = _DEFAULT_Z_HI_M,
    rasterize_fallback: bool = False,
    write: bool = True,
    occupancy_out: Path | None = None,
) -> dict[str, Any]:
    """Compute the connectivity graph for one scene and (optionally) author it.

    Returns a result dict with the rooms, edges, flags, and occupancy meta —
    suitable for logging/reporting whether or not ``write`` is set.
    """
    import omni.usd  # type: ignore
    from pxr import UsdPhysics  # type: ignore

    ctx = omni.usd.get_context()
    _trace(f"opening stage {usd_path}")
    if not ctx.open_stage(str(usd_path)):
        raise RuntimeError(f"omni.usd failed to open stage: {usd_path}")
    _wait_for_stage_load(ctx, simulation_app)
    stage = ctx.get_stage()
    _trace("stage ready; reading metadata + recovering rooms")

    metadata = scene_metadata_reader.read_custom_data(stage) or {}
    metadata.setdefault("rooms", [])
    metadata.setdefault("objects", [])
    metadata.setdefault("room_adjacency", [])

    recovered, floor_z = recover_rooms_from_floors(stage)
    backfilled_rooms = False
    rooms = metadata["rooms"]
    if not rooms:
        rooms = recovered
        metadata["rooms"] = rooms
        backfilled_rooms = True
        logger.info("Back-filled rooms[] from floor meshes (%d rooms)", len(rooms))
    if not rooms:
        raise RuntimeError("no rooms in metadata and none recoverable from floor meshes")

    doors = collect_door_prims(stage)
    bounds = _scene_bounds(rooms, pad_m)
    z_min, z_max = floor_z + z_lo_m, floor_z + z_hi_m
    _trace(
        f"rooms={len(rooms)} doors={len(doors)} bounds={tuple(round(b,2) for b in bounds)} "
        f"z=[{z_min:.2f},{z_max:.2f}] mode={'raster' if rasterize_fallback else 'omap'}"
    )

    # Ensure a physics scene exists for the occupancy raycasts. Track whether we
    # added it so we don't persist a scene-gen-only physics prim into the USD.
    added_physics = False
    physics_path = "/World/connectivityPhysicsScene"
    if not rasterize_fallback and not any(
        p.IsA(UsdPhysics.Scene) for p in stage.Traverse()
    ):
        from pxr import Sdf  # type: ignore

        UsdPhysics.Scene.Define(stage, Sdf.Path(physics_path))
        added_physics = True

    # Door-open guarantee: the mecanum strafer can't open doors, so the harness
    # authors them open at scene-gen time (the brief's "doors assumed open"). Drop
    # every door's collider BEFORE generating occupancy — doing it up front means
    # the single PhysX cook on timeline.play() never sees the closed panels, which
    # is robust where a post-gen RemoveAPI + re-cook is not. The leaf panel is also
    # hidden so the visual matches the now-open passage (a demo camera must not
    # film the robot driving through a shut-looking door). Both are persisted on
    # write so the runtime scene + occupancy match. (NOTE: the omap can still mark
    # a room sealed only by a meshSimplification-healed wall cutout as occupied —
    # a separate occupancy-fidelity limitation tracked as a follow-up, not a
    # door-matching gap.)
    forced_open = 0
    if not rasterize_fallback and doors:
        forced_open = drop_door_colliders(stage, [d["path"] for d in doors])
        hidden = hide_door_leaves(stage, [d["path"] for d in doors if d["is_leaf"]])
        for _ in range(3):
            simulation_app.update()
        _trace(
            f"force-opened {forced_open} door collider(s), hid {hidden} leaf mesh(es) "
            f"across {len(doors)} door prim(s)"
        )

    _trace("generating occupancy")
    occupancy, origin_xy = generate_occupancy_omap(
        simulation_app, bounds=bounds, z_min=z_min, z_max=z_max, cell_size=cell_size,
    ) if not rasterize_fallback else generate_occupancy_rasterize(
        stage, rooms, metadata, bounds=bounds, z_min=z_min, z_max=z_max, cell_size=cell_size,
    )
    _trace(f"occupancy shape={occupancy.shape} occupied={int(occupancy.sum())}")
    free = scene_connectivity.occupancy_to_free_space(occupancy, grid_res=cell_size)
    room_adjacency = metadata.get("room_adjacency") or None
    edges = scene_connectivity.compute_connectivity(
        rooms, free, grid_origin_xy=origin_xy, grid_res=cell_size,
        room_adjacency=room_adjacency,
    )
    cross_reach = sum(1 for e in edges if e.get("reachable") and e["from_idx"] != e["to_idx"])
    _trace(f"computed {len(edges)} edges ({cross_reach} cross-room reachable)")

    # Tag door_state on reachable edges: a door prim sitting on the crossing was
    # force-opened (this run or a prior one — re-processing an already-opened
    # scene drops 0 colliders but the door is still there), otherwise the passage
    # is an open gap. Keyed on a door at the crossing, not on this run's drop count.
    opened_doors = doors if not rasterize_fallback else []
    for e in edges:
        if not e.get("reachable"):
            continue
        e["door_state"] = "force-opened" if _door_at_crossing(e, opened_doors) else "absent"

    multi_story = scene_connectivity.is_multi_story(rooms)
    incompatible = scene_connectivity.is_multi_room_incompatible(edges)
    metadata["connectivity"] = edges
    metadata["multi_story"] = multi_story
    if incompatible:
        metadata["multi_room_incompatible"] = True
    else:
        metadata.pop("multi_room_incompatible", None)

    # Cache the occupancy sidecar (regenerable derived intermediate).
    scene_dir = _scene_dir_for(usd_path)
    st = usd_path.resolve().stat()
    occ_meta = scene_connectivity.occupancy_meta(
        origin_xy=origin_xy, resolution_m=cell_size, z_min_m=z_min, z_max_m=z_max,
        usd_path=str(usd_path.resolve()), usd_mtime_ns=st.st_mtime_ns, usd_size=st.st_size,
    )

    if write:
        if added_physics:  # don't persist the scene-gen-only physics prim
            stage.RemovePrim(physics_path)
        scene_metadata_reader.write_custom_data(stage, metadata)
        ctx.save_stage()
        scene_connectivity.save_occupancy(scene_dir, occupancy, occ_meta)
        _trace(f"authored connectivity[] into USD + cached occupancy in {scene_dir}")
    else:
        _trace("computed connectivity (no-write: USD + occupancy cache left untouched)")

    if occupancy_out is not None:  # debug/inspection dump, independent of --write
        occupancy_out.mkdir(parents=True, exist_ok=True)
        scene_connectivity.save_occupancy(occupancy_out, occupancy, occ_meta)
        (occupancy_out / "rooms.json").write_text(json.dumps(rooms, indent=2), encoding="utf-8")
        _trace(f"dumped occupancy + rooms to {occupancy_out}")

    return {
        "usd_path": str(usd_path),
        "rooms": rooms,
        "edges": edges,
        "multi_story": multi_story,
        "multi_room_incompatible": incompatible,
        "backfilled_rooms": backfilled_rooms,
        "occupancy_meta": occ_meta,
        "occupancy_shape": list(occupancy.shape),
    }


def _boot_kit() -> Any:
    """Boot a headless Isaac Sim Kit app with physics + the omap extension."""
    from isaaclab.app import AppLauncher  # type: ignore

    parser = argparse.ArgumentParser(add_help=False)
    AppLauncher.add_app_launcher_args(parser)
    kit_args = parser.parse_args([])
    kit_args.headless = True
    kit_args.enable_cameras = True
    app = AppLauncher(kit_args).app
    try:
        from isaacsim.core.utils.extensions import enable_extension  # type: ignore

        enable_extension("isaacsim.asset.gen.omap")
        app.update()
    except Exception as exc:  # noqa: BLE001
        logger.warning("could not enable isaacsim.asset.gen.omap: %s", exc)
    return app


def _cli_main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--usd", type=Path, required=True, help="Scene USD to process.")
    parser.add_argument("--cell-size", type=float, default=scene_connectivity.DEFAULT_RESOLUTION_M)
    parser.add_argument("--pad-m", type=float, default=_DEFAULT_PAD_M)
    parser.add_argument("--z-lo-m", type=float, default=_DEFAULT_Z_LO_M)
    parser.add_argument("--z-hi-m", type=float, default=_DEFAULT_Z_HI_M)
    parser.add_argument(
        "--rasterize-fallback", action="store_true",
        help="Build occupancy from room footprints + object AABBs instead of the "
             "occupancy-map extension (use when omap is unavailable).",
    )
    parser.add_argument(
        "--no-write", action="store_true",
        help="Compute + report only; do not author customData or cache occupancy.",
    )
    parser.add_argument("--json-out", type=Path, default=None, help="Write the result dict here.")
    parser.add_argument(
        "--occupancy-out", type=Path, default=None,
        help="Dump occupancy.npy + occupancy.json + rooms.json to this dir for "
             "inspection (independent of --no-write).",
    )
    parser.add_argument(
        "--log-file", type=Path, default=Path("/tmp/validate_scene_connectivity.log"),
        help="Mirror progress + errors here (Kit hijacks stdout, so a file log is "
             "the reliable trace).",
    )
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    if not args.usd.exists():
        logger.error("USD not found: %s", args.usd)
        return 2

    global _TRACE_PATH
    _TRACE_PATH = args.log_file
    if _TRACE_PATH is not None:
        _TRACE_PATH.write_text("", encoding="utf-8")  # fresh trace per run

    _trace(f"booting Kit for {args.usd}")
    simulation_app = _boot_kit()
    rc = 0
    try:
        result = validate_connectivity(
            args.usd, simulation_app=simulation_app, cell_size=args.cell_size,
            pad_m=args.pad_m, z_lo_m=args.z_lo_m, z_hi_m=args.z_hi_m,
            rasterize_fallback=args.rasterize_fallback, write=not args.no_write,
            occupancy_out=args.occupancy_out,
        )
        # Persist the result inside the try — it lands before teardown either way.
        _report_result(result, args.json_out)
    except Exception:
        _trace("connectivity validation FAILED:\n" + traceback.format_exc())
        if args.json_out is not None:
            args.json_out.write_text(
                json.dumps({"error": traceback.format_exc(), "usd_path": str(args.usd)}, indent=2),
                encoding="utf-8",
            )
        rc = 1

    # Kit's simulation_app.close() reliably hangs/segfaults on teardown here and
    # leaves a zombie holding the GPU, which collides with the next launch. The
    # USD save + occupancy cache + result JSON already landed above, so hard-exit
    # and let the OS reclaim Kit (the same os._exit pattern the lab Kit tests use).
    _trace(f"exiting rc={rc}")
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(rc)


def _report_result(result: dict[str, Any], json_out: Path | None) -> None:
    rooms, edges = result["rooms"], result["edges"]
    reachable = sum(1 for e in edges if e.get("reachable"))
    cross_reach = sum(1 for e in edges if e.get("reachable") and e["from_idx"] != e["to_idx"])
    matrix_str = _format_matrix(rooms, edges)
    _trace(
        f"{Path(result['usd_path']).name}: {len(rooms)} rooms, {len(edges)} edges "
        f"({reachable} reachable, {cross_reach} cross-room), "
        f"multi_story={result['multi_story']} "
        f"multi_room_incompatible={result['multi_room_incompatible']}"
    )
    _trace("Connectivity matrix (# = reachable):\n" + matrix_str)
    _trace("Edges:\n" + "\n".join("  " + json.dumps(e) for e in edges))
    print("\nConnectivity matrix (# = reachable):\n" + matrix_str, flush=True)
    if json_out is not None:
        json_out.write_text(json.dumps(result, indent=2), encoding="utf-8")
        _trace(f"wrote result to {json_out}")


if __name__ == "__main__":  # pragma: no cover
    sys.exit(_cli_main())
