#!/usr/bin/env python3
"""Enforce env single-source: the compose mirrors are GENERATED from canon, and
every key has exactly ONE home.

deploy/compose/*.env are generated by gen_env.py from the canonical
strafer_bringup/config/env_*.env. This check regenerates them in-memory and
byte-diffs against the committed files, so ANY drift -- including the
CYCLONEDDS_URI the old overlap-diff silently skipped -- fails.

THE PARTITION RULE, and why it is the shape it is. Three compose behaviours
were measured, and together they leave exactly one workable rule:

  * an overlay's `env_file` APPENDS to the base list rather than replacing it,
    so lane mirrors compose;
  * for a duplicate key the LAST file wins, so a lane mirror layers over canon;
  * a service `environment:` key BEATS `env_file:` -- but a bare
    `environment: - VAR` with no value DELETES the env_file value when the host
    does not set it, so the key vanishes from the container entirely.

The third one is what forecloses the obvious alternative: no key can be both
env_file-defaulted and host-overridable. So a key lives in a generated env_file
(canon-owned, reviewed, not host-overridable) OR in an overlay `environment:`
as `${VAR:-default}` (host-overridable, absent from every env_file). Never
both -- a key in both homes is a silent shadow, where a canon edit plus
`make env-sync` changes nothing in the container. That is enforced structurally
below rather than left to review.

The invariants beyond the regenerate+diff:

  1. DDS URI consistency: the container CYCLONEDDS_URI is identical across the
     docker-compose{,.sim}.yml x-dds-env anchors and equals the cyclonedds.xml
     bind-mount target. (The one non-portable key lives only in compose.)
  2. Deploy-only keys (each lane's declared generator overlay) are present in
     that lane's mirror and absent from its canon.
  3. The sim-only freshness widenings never leak into the autonomy lane
     (the REAL-HARDWARE GUARD comment, as an executable assertion), and the
     sim-bridge mirror that carries them is loaded by no always-on lane.
  4. THE PARTITION: no key appears in both a generated mirror and a compose
     service's `environment:`.
  5. Container-env passthrough, the other half of "how does a value reach a
     node": a key a launch file reads from os.environ INSIDE its container
     needs an `environment:` mapping, because a host export or deploy/.env
     only feeds compose interpolation. Same failure shape as a shadow -- the
     knob is silently inert -- so it is checked in the same place.

Run:  python3 deploy/tests/check_env_sync.py     (or `make env-check`)   0 = OK
"""
import re
import sys
from pathlib import Path

import gen_env  # sibling module (its dir is on sys.path when run as a script)

HERE = Path(__file__).resolve().parent
DEPLOY = HERE.parent
CANON = DEPLOY.parent / "strafer_bringup" / "config"
COMPOSE = DEPLOY / "compose"

CONTAINER_URI = "file:///opt/strafer/config/cyclonedds.xml"
# Env vars a launch file reads from os.environ INSIDE its container, mapped to
# the compose file + service that must pass them through.
CONTAINER_ENV_PASSTHROUGH = {
    ("docker-compose.yml", "slam"): (
        "STRAFER_SLAM_TASK_ID", "STRAFER_SLAM_SCENE_TOKEN",
    ),
    ("docker-compose.sim.yml", "strafer-sim"): (
        "STRAFER_SLAM_TASK_ID", "STRAFER_SLAM_SCENE_TOKEN",
    ),
}
# sim-only freshness widenings that must never reach the real-robot autonomy lane
WIDENING_KEYS = {
    "OBSERVATION_MAX_AGE_S",
    "STRAFER_OBS_TIMEOUT_S",
    "STRAFER_DEPTH_TIMEOUT_S",
    "ROTATE_TIMEOUT_S",
    "STRAFER_PROJECTION_DEPTH_MAX_M",
    "STRAFER_NAVIGATION_TIMEOUT_S",
}
COMPOSE_FILES = ("docker-compose.yml", "docker-compose.sim.yml")
# Every tracked compose file whose service `environment:` blocks form the
# host-lever half of the partition. The untracked host overlays are per-machine
# and out of scope -- the README says so, and this check cannot see them.
PARTITIONED_COMPOSE_FILES = COMPOSE_FILES + (
    "docker-compose.override.sim-bridge.yml",
)
# Mirrors that carry sim-only values and must be loaded ONLY by the opt-in
# overlay, never by a lane that comes up by default.
SIM_ONLY_MIRRORS = ("compose/sim_bridge.env",)


def _mirror_keys(path: Path):
    keys = set()
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"^([A-Z0-9_]+)=", line)
        if m:
            keys.add(m.group(1))
    return keys


def _canon_keys(path: Path):
    return {k for k, _ in gen_env.parse_canon(path)}


def _service_env(svc: dict):
    """Keys in one service's `environment:`, in either compose form."""
    env = (svc or {}).get("environment") or {}
    if isinstance(env, list):                   # "KEY=value" / bare "KEY" form
        return {item.split("=", 1)[0] for item in env}
    return set(env)


def _env_files(svc: dict):
    """`env_file:` entries of one service, in either compose form."""
    entry = (svc or {}).get("env_file") or []
    return [entry] if isinstance(entry, str) else list(entry)


def main() -> int:
    fails = []

    # 1. mirrors == gen_env(canon), byte for byte
    for name in gen_env.LANES:
        expected = gen_env.render(name)
        actual = (COMPOSE / name).read_text()
        if expected != actual:
            fails.append(f"{name}: drifted from canon -- run `make env-sync` to regenerate")

    # 2. container URI consistency across compose anchors + bind-mount targets
    uris, mounts = set(), set()
    for yml in COMPOSE_FILES:
        for line in (DEPLOY / yml).read_text().splitlines():
            if line.lstrip().startswith("#"):   # skip prose (e.g. the zenoh "NO CYCLONEDDS_URI:" note)
                continue
            m = re.search(r"CYCLONEDDS_URI:\s*(\S+)", line)
            if m:
                uris.add(m.group(1))
            mounts.update(re.findall(r"cyclonedds\.xml:(/\S+?):ro", line))
    if not uris:
        fails.append("no CYCLONEDDS_URI in the compose x-dds-env anchors (expected the container path)")
    for u in sorted(uris):
        if u != CONTAINER_URI:
            fails.append(f"compose CYCLONEDDS_URI={u!r} != expected {CONTAINER_URI!r}")
    for mnt in sorted(mounts):
        if f"file://{mnt}" != CONTAINER_URI:
            fails.append(f"cyclonedds.xml bind-mount target {mnt!r} != URI path in {CONTAINER_URI!r}")

    # 3. each lane's declared deploy-only keys: present in mirror, absent in canon
    for name, spec in gen_env.LANES.items():
        mk = _mirror_keys(COMPOSE / name)
        ck = _canon_keys(CANON / spec["canon"])
        for k, _ in spec["overlay"]:
            if k not in mk:
                fails.append(f"{name}: deploy-only {k} missing from mirror")
            if k in ck:
                fails.append(f"{spec['canon']}: deploy-only {k} unexpectedly present in canon")

    # 4. REAL-HARDWARE GUARD: sim widenings never leak into the autonomy lane
    leaked = WIDENING_KEYS & (
        _mirror_keys(COMPOSE / "autonomy.env") | _canon_keys(CANON / "env_autonomy.env")
    )
    for k in sorted(leaked):
        fails.append(f"REAL-HARDWARE GUARD: sim-only widening {k} leaked into the autonomy lane")

    try:
        import yaml  # pyyaml ships with the ROS images and the dev hosts
    except ImportError:                         # pragma: no cover
        print("pyyaml missing -- skipped the compose-side invariants")
        yaml = None

    if yaml is not None:
        specs = {
            yml: yaml.safe_load((DEPLOY / yml).read_text())
            for yml in PARTITIONED_COMPOSE_FILES
        }

        # 4b. the mirrors carrying sim-only values stay behind the opt-in
        #     overlay: an always-on lane loading one would widen the real robot.
        for yml in COMPOSE_FILES:
            for service, svc in (specs[yml].get("services") or {}).items():
                for entry in _env_files(svc):
                    if entry in SIM_ONLY_MIRRORS:
                        fails.append(
                            f"{yml}: service {service!r} loads {entry}, which "
                            "carries sim-only values; it belongs only to the "
                            "opt-in sim-bridge overlay"
                        )

        # 5. THE PARTITION: one key, one home. A key in both a generated mirror
        #    and a service `environment:` is a shadow -- `environment:` wins, so
        #    a canon edit plus `make env-sync` would be silently inert.
        mirrored = {}
        for name in gen_env.LANES:
            for key in _mirror_keys(COMPOSE / name):
                mirrored.setdefault(key, []).append(name)
        for yml in PARTITIONED_COMPOSE_FILES:
            for service, svc in (specs[yml].get("services") or {}).items():
                for key in _service_env(svc):
                    if key in mirrored:
                        homes = ", ".join(sorted(mirrored[key]))
                        fails.append(
                            f"PARTITION: {key} has two homes -- generated "
                            f"{homes} and {yml}'s {service!r} `environment:`. "
                            "`environment:` beats `env_file:`, so the canon "
                            "edit would be silently inert. Pick one: canon-owned "
                            "in the mirror, or `${VAR:-default}` here and "
                            "removed from every canon file."
                        )

        # 6. container-env passthrough, the partition's other half: a knob the
        #    launch file reads inside the container must be mapped by its
        #    service, or setting it on the host does nothing.
        for (yml, service), keys in CONTAINER_ENV_PASSTHROUGH.items():
            env = _service_env((specs[yml].get("services") or {}).get(service) or {})
            for key in keys:
                if key not in env:
                    fails.append(
                        f"{yml}: service {service!r} does not pass {key} through to "
                        "the container; the launch file reads it from os.environ "
                        "there, so a host export or deploy/.env would be inert"
                    )

    if fails:
        print("ENV SINGLE-SOURCE / INVARIANT FAILURES:")
        for f in fails:
            print("  " + f)
        return 1
    print(
        "env single-source OK: mirrors == gen_env(canon); one key one home "
        "(partition + passthrough); DDS-URI + deploy-only + real-hw-guard hold"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
