#!/usr/bin/env python3
"""Enforce env single-source: the compose mirrors are GENERATED from canon.

deploy/compose/{sim,autonomy}.env are generated by gen_env.py from the canonical
strafer_bringup/config/env_*.env. This check regenerates them in-memory and
byte-diffs against the committed files, so ANY drift -- including the
CYCLONEDDS_URI the old overlap-diff silently skipped -- fails. Plus three
invariants that guard what the regenerate+diff alone cannot:

  1. DDS URI consistency: the container CYCLONEDDS_URI is identical across the
     docker-compose{,.sim}.yml x-dds-env anchors and equals the cyclonedds.xml
     bind-mount target. (The one non-portable key now lives only in compose.)
  2. Deploy-only keys (VLM_URL / PLANNER_URL) are present in the mirror and
     absent from canon.
  3. The sim-only freshness widenings never leak into the autonomy lane
     (the REAL-HARDWARE GUARD comment, as an executable assertion).

Run:  python3 deploy/tests/check_env_sync.py     (or `make env-check`)   0 = OK
"""
import re
import sys
from pathlib import Path

import gen_env  # sibling module (its dir is on sys.path when run as a script)

HERE = Path(__file__).resolve().parent
DEPLOY = HERE.parent
CANON = DEPLOY.parent / "strafer_bringup" / "config"
COMPOSE = DEPLOY / "compose"

CONTAINER_URI = "file:///opt/strafer/config/cyclonedds.xml"
DEPLOY_ONLY = ("VLM_URL", "PLANNER_URL")
# sim-only freshness widenings that must never reach the real-robot autonomy lane
WIDENING_KEYS = {
    "OBSERVATION_MAX_AGE_S",
    "STRAFER_OBS_TIMEOUT_S",
    "STRAFER_DEPTH_TIMEOUT_S",
    "ROTATE_TIMEOUT_S",
    "STRAFER_PROJECTION_DEPTH_MAX_M",
    "STRAFER_NAVIGATION_TIMEOUT_S",
}
COMPOSE_FILES = ("docker-compose.yml", "docker-compose.sim.yml")


def _mirror_keys(path: Path):
    keys = set()
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"^([A-Z0-9_]+)=", line)
        if m:
            keys.add(m.group(1))
    return keys


def _canon_keys(path: Path):
    return {k for k, _ in gen_env.parse_canon(path)}


def main() -> int:
    fails = []

    # 1. mirrors == gen_env(canon), byte for byte
    for name in gen_env.LANES:
        expected = gen_env.render(name)
        actual = (COMPOSE / name).read_text()
        if expected != actual:
            fails.append(f"{name}: drifted from canon -- run `make env-sync` to regenerate")

    # 2. container URI consistency across compose anchors + bind-mount targets
    uris, mounts = set(), set()
    for yml in COMPOSE_FILES:
        for line in (DEPLOY / yml).read_text().splitlines():
            if line.lstrip().startswith("#"):   # skip prose (e.g. the zenoh "NO CYCLONEDDS_URI:" note)
                continue
            m = re.search(r"CYCLONEDDS_URI:\s*(\S+)", line)
            if m:
                uris.add(m.group(1))
            mounts.update(re.findall(r"cyclonedds\.xml:(/\S+?):ro", line))
    if not uris:
        fails.append("no CYCLONEDDS_URI in the compose x-dds-env anchors (expected the container path)")
    for u in sorted(uris):
        if u != CONTAINER_URI:
            fails.append(f"compose CYCLONEDDS_URI={u!r} != expected {CONTAINER_URI!r}")
    for mnt in sorted(mounts):
        if f"file://{mnt}" != CONTAINER_URI:
            fails.append(f"cyclonedds.xml bind-mount target {mnt!r} != URI path in {CONTAINER_URI!r}")

    # 3. deploy-only keys present in mirror, absent in canon
    for name, spec in gen_env.LANES.items():
        mk = _mirror_keys(COMPOSE / name)
        ck = _canon_keys(CANON / spec["canon"])
        for k in DEPLOY_ONLY:
            if k not in mk:
                fails.append(f"{name}: deploy-only {k} missing from mirror")
            if k in ck:
                fails.append(f"{spec['canon']}: deploy-only {k} unexpectedly present in canon")

    # 4. REAL-HARDWARE GUARD: sim widenings never leak into the autonomy lane
    leaked = WIDENING_KEYS & (
        _mirror_keys(COMPOSE / "autonomy.env") | _canon_keys(CANON / "env_autonomy.env")
    )
    for k in sorted(leaked):
        fails.append(f"REAL-HARDWARE GUARD: sim-only widening {k} leaked into the autonomy lane")

    if fails:
        print("ENV SINGLE-SOURCE / INVARIANT FAILURES:")
        for f in fails:
            print("  " + f)
        return 1
    print("env single-source OK: mirrors == gen_env(canon); DDS-URI + deploy-only + real-hw-guard invariants hold")
    return 0


if __name__ == "__main__":
    sys.exit(main())
