#!/usr/bin/env python3
"""Generate the compose env_file mirrors from the canonical bringup env files.

SINGLE SOURCE OF TRUTH: strafer_bringup/config/env_*.env (hand-edited, shell
`export KEY=VALUE`, with the rationale comments). The plain KEY=VALUE compose
mirrors under deploy/compose/ are GENERATED from them by this script -- do NOT
hand-edit the mirrors.

Why generate instead of share one file: docker-compose `env_file` is parsed as
plain KEY=VALUE (no shell), so it cannot express the canonical self-locating
`CYCLONEDDS_URI="file://$(dirname ...)/cyclonedds.xml"`. Rather than hard-code a
container path in the mirror, we DROP the DDS vars entirely: every compose
service draws RMW/CYCLONEDDS_URI/ROS_DOMAIN_ID from the shared `x-dds-env` anchor
in docker-compose{,.sim}.yml. So the mirror carries only portable KEY=VALUE
knobs, and the one genuinely non-portable key (the container URI) lives in exactly
one place per lane -- the compose anchor. Deploy-only keys with no canonical home
(VLM_URL / PLANNER_URL) are appended from a declared per-lane overlay.

  python3 gen_env.py            # print both mirrors to stdout (dry run)
  python3 gen_env.py --write    # write deploy/compose/{sim,autonomy}.env

check_env_sync.py (a.k.a. `make env-check`) regenerates in-memory and byte-diffs
against the committed mirrors, so any drift fails.
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent                 # deploy/tests
DEPLOY = HERE.parent                                   # deploy
CANON = DEPLOY.parent / "strafer_bringup" / "config"   # strafer_ros/strafer_bringup/config
COMPOSE = DEPLOY / "compose"

# Supplied by the compose x-dds-env anchor (docker-compose{,.sim}.yml), never the
# env_file -- so the self-locating `$(...)` URI never has to reach a container and
# the mirror stays purely portable KEY=VALUE.
DDS_ANCHOR_KEYS = ("RMW_IMPLEMENTATION", "CYCLONEDDS_URI", "ROS_DOMAIN_ID")

_BANNER = (
    "# GENERATED by `make env-sync` (deploy/tests/gen_env.py) -- DO NOT EDIT.\n"
    "# Single source of truth: strafer_bringup/config/{canon} (rationale lives\n"
    "# there). Edit that file, then run `make env-sync`; `make env-check` fails on\n"
    "# drift. DDS vars (RMW/CYCLONEDDS_URI/ROS_DOMAIN_ID) come from the compose\n"
    "# x-dds-env anchor, not this file."
)

# Deploy-only keys that have no canonical counterpart, appended per lane. The
# autonomy overlay header also carries the load-bearing REAL-HARDWARE GUARD
# (check_env_sync enforces the widening-key absence as well).
LANES = {
    "sim.env": {
        "canon": "env_sim_in_the_loop.env",
        "overlay_header": (
            "# Remote VLM / planner services on the sim host (deploy-only; no\n"
            "# canonical counterpart). Point these at wherever the Isaac Sim host\n"
            "# runs them."
        ),
        "overlay": (
            ("VLM_URL", "http://192.168.50.196:8100"),
            ("PLANNER_URL", "http://192.168.50.196:8200"),
        ),
    },
    "autonomy.env": {
        "canon": "env_autonomy.env",
        "overlay_header": (
            "# Remote VLM / planner services -- set to your real hosts. Empty here\n"
            "# means the executor's startup health-check fails (by design) until set.\n"
            "#\n"
            "# REAL-HARDWARE GUARD: do NOT add STRAFER_DEPTH_TIMEOUT_S /\n"
            "# STRAFER_OBS_TIMEOUT_S / OBSERVATION_MAX_AGE_S here. Those are sim-only\n"
            "# freshness widenings (see env_sim_in_the_loop.env); on the real robot\n"
            "# the canonical tight defaults (~0.5 s / 0.2 s) must stand, or a stalled\n"
            "# perception/inference stream gets masked. check_env_sync enforces this."
        ),
        "overlay": (
            ("VLM_URL", ""),
            ("PLANNER_URL", ""),
        ),
    },
}

_EXPORT = re.compile(r"^export\s+([A-Z0-9_]+)=(.*)$")


def _unquote(v: str) -> str:
    v = v.strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":
        v = v[1:-1]
    return v


def parse_canon(path: Path):
    """Ordered [(key, value)] from a canonical `export KEY=VALUE` file."""
    out = []
    for line in path.read_text().splitlines():
        m = _EXPORT.match(line.strip())
        if m:
            out.append((m.group(1), _unquote(m.group(2))))
    return out


def render(mirror_name: str) -> str:
    """Render the plain KEY=VALUE mirror text for one lane (deterministic)."""
    spec = LANES[mirror_name]
    lines = [_BANNER.format(canon=spec["canon"]), ""]
    for key, value in parse_canon(CANON / spec["canon"]):
        if key in DDS_ANCHOR_KEYS:
            continue
        lines.append(f"{key}={value}")
    lines.append("")
    lines.append(spec["overlay_header"])
    for key, value in spec["overlay"]:
        lines.append(f"{key}={value}")
    return "\n".join(lines) + "\n"


def main(argv) -> int:
    write = "--write" in argv
    for name in LANES:
        text = render(name)
        if write:
            (COMPOSE / name).write_text(text)
            print(f"wrote {(COMPOSE / name).relative_to(DEPLOY.parent.parent.parent)}")
        else:
            print(f"===== {name} =====")
            print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
